### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by bingochen87** [hedeqiang/UMeng-Push#17]
NOTICE: PHP message: PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST http://msg.umeng.com/api/send?sign=96ddb80093247a8618bc2f122fd2fc79` resulted in a `400 Bad Request` response in /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /var/www/html/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/html/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /var/www/html/vendor/guzzlehttp/promises/src/ in /var/www/html/vendor/hedeqiang/umeng/src/Android.php on line 77

**Comment by ieliwb** [comment]
大佬怎么解决的啊，我也运行报这个 @bingochen87
