### ISSUE TITLE
推送过程，报错编码格式不正确

### ISSUE THREAD

**Issue by 15721542767** [hedeqiang/UMeng-Push#24]
@hedeqiang

**Comment by hedeqiang** [comment]
贴代码，如何使用的？ 这个包安装人数 已经快超 1k 了，所以应该是没太大问题的

**Comment by 15721542767** [comment]
```php
public static function sendAppIosMsg($Iosinfo,$title,$content){
        $Iosinfo = array_column($Iosinfo,'mac');//获取ios系统的设备标识
        $ios_config = [
            'appKey' => config('global.app_key_ios'),
            'appMasterSecret' => config('global.master_secret_ios'),
            'production_mode' => true,
        ];
        $ios = new IOS($ios_config);
        $params = [
            'device_tokens' => $Iosinfo,
            'alert' => [
                'title' => $title,
                'body' => $content,
            ],
        ];
        $customized = [
            'key' => 'jey',
        ];
        $response = $ios->sendIOSUnicast($params,$customized);
        
    }
```
上面是代码，调用的方法，然后走到下面这个文件：hedeqiang\umeng\src\notification\UmengNotification.php里面的send()方法，里面try里面代码报错，格式不正确：
```php
try {
            $client = new Client();
            $response = $client->request('POST', $url, [
                'body' => $postBody,
            ]);

            return \json_decode($response->getBody()->getContents(), true);
        } catch (\Exception $e) {
            throw new HttpException($e->getMessage(), $e->getCode(), $e);
        }
```

**Comment by 15721542767** [comment]
我感觉应该是调用的这个方法：use GuzzleHttp\Client; 没有utf8编码格式

**Comment by hedeqiang** [comment]
你的 title  、content 发的内容是什么？

**Comment by 15721542767** [comment]
数字和汉字，但是无论是数字还是汉字都有这个错误

**Comment by 15721542767** [comment]
在send()方法里面打印$postBody变量 dd($postBody);是有数据如下：
"{"appkey":"5f6edfc4906ad81117150616","timestamp":"1602829389","type":"unicast","production_mode":true,"payload":{"aps":{"alert":{"title":"121212121","body":"1212121212"}},"key":"jey"},"device_tokens":["fa4c19fecd244e1225752ea53c0762d35586ec3347d1867c488278d7adb942de"]}"

public function send()
    {
        //check the fields to make sure that they are not NULL
        $this->isComplete();

        $url = $this->host.$this->postPath;
        $postBody = json_encode($this->data);
        dd($postBody);
        $sign = md5('POST'.$url.$postBody.$this->appMasterSecret);
        $url = $url.'?sign='.$sign;

        try {
            $client = new Client();
            $response = $client->request('POST', $url, [
                'body' => $postBody,
            ]);

            return \json_decode($response->getBody()->getContents(), true);
        } catch (\Exception $e) {
            throw new HttpException($e->getMessage(), $e->getCode(), $e);
        }
    }

**Comment by hedeqiang** [comment]
把错误信息发一下 @15721542767

**Comment by 15721542767** [comment]
message: "Malformed UTF-8 characters, possibly incorrectly encoded"

**Comment by hedeqiang** [comment]
我这边测试 Android 正常 ， iOS ，我没有账号 所以....但是最终都会走到 send 方法，所以也不会有问题。是不是你的文件编码有问题？
你是什么框架？

**Comment by 15721542767** [comment]
lavaral框架

**Comment by hedeqiang** [comment]
我也是，我刚才在 Laravel 7 上面测试的 Android

**Comment by 15721542767** [comment]
我没有使用Android 使用的iOS

**Comment by hedeqiang** [comment]
抱歉，我没 iOS 应用，不好测试

**Comment by hedeqiang** [comment]
你帮着调试一下，看下其他方式呢？ 比如 customizedcast 呢？ 还是说你只能使用  unicast

**Comment by hedeqiang** [comment]
unicast 消息发送示例
```php
// Android
{
    "appkey":"你的appkey",
    "timestamp":"你的timestamp",
    "type":"unicast",
    "production_mode":"false",
    "device_tokens":"xx(Android为44位)",
    "payload": {
        "display_type": "message",   // 消息，message
        "body": {
            "custom":"自定义custom"/{} // message类型只需填写custom即可，可以是字符串或JSON。
        }
    },
    "policy": {
        "expire_time": "2013-10-30 12:00:00"
    },
    "description":"测试单播消息-Android"
}

// iOS
{
    "appkey":"你的appkey",
    "timestamp":"你的timestamp",
    "type":"unicast",
    "production_mode":"false",
    "device_tokens":"xx(iOS为64位)", 
    "payload": {
        "aps":{    // 苹果必填字段
            "alert":""/{    // 当content-available=1时(静默推送)，可选; 否则必填。
                            // 可为JSON类型和字符串类型
                "title":"title",
                "subtitle":"subtitle",
                "body":"body"
            }
        }
        "k1":"v1",    // 自定义key-value, key不可以是"d","p"
        "k2":"v2",
        ...
    },
    "policy": {
        "expire_time":"2013-10-30 12:00:00"
    },
    "description":"测试单播消息-iOS"
}
```

**Comment by 15721542767** [comment]
昨天使用官网文档里面的send方法 编码格式问题解决了；请教个问题：使用unicast推送，返回信息是推送成功，但是接收不到，使用Broadcast推送可以接收到

**Comment by hedeqiang** [comment]
看下 终端吧，发送成功，问题就是在终端了吧  ，话说 官网 send 有什么不同吗？
