### ISSUE TITLE
请问为什么不集成 listcast ？

### ISSUE THREAD

**Issue by YanCunJu** [hedeqiang/UMeng-Push#25]
官方的 demo 文档中也没有，但是有 AndroidListcast 这个类文件，请问使用或集成列播有什么问题？

**Comment by hedeqiang** [comment]
我这个是基于官方 demo 做的，如果demo 没有，我这里可能也没有，欢迎提交 PR

**Comment by hedeqiang** [comment]
我看了下 代码中是有的，可以提一个 PR，因为我目前无法测试，您方便帮忙提个 PR， 加一个类吗？

**Comment by hedeqiang** [comment]
我重新打了一个包 添加了 listcast ,你帮着测试一下吧，谢了， @YanCunJu

**Comment by hedeqiang** [comment]
发布了 v2.x 可以去试下，当然 v1.x 也是可以使用，只不过不如 v2.x 使用简单
